In [3]:
import numpy as np
from localization import local_to_global, global_to_local
#from planning_utils import create_grid

In [39]:
#global_coord = (-122.396591, 37.793405, 0.0) 
global_coord = (-122.397450, 37.792480, 0)

In [40]:
all_lon=[]
all_lat=[]
for n in range(-316,605,10):
    for e in range(-445,476,10):
        global_c = local_to_global((n,e,0), global_coord)
        all_lon.append(global_c[0])
        all_lat.append(global_c[1])

In [41]:
print ("Longitude between {} and {}".
       format(np.array(all_lon).min(),
              np.array(all_lon).max()))

print ("Latitude between {} and {}".
       format(np.array(all_lat).min(),
              np.array(all_lat).max()))

Longitude between -122.40107128542968 and -122.39055502515198
Latitude between 37.788434060869996 and 37.79677934306897


In [65]:
ned_coord_list = [(296, -81, 3), (0, 0, 0), (100, 100, 0), (407, -36, 0), 
             (95, -276, 0), (-63, -129, 0), (248, 79, 0), (183, -178, 0)]

In [76]:
global_c = []
for ned in ned_coord_list:
    end = (ned[1], ned[0], ned[2])
    global_c.append(local_to_global(end, global_coord))

In [77]:
global_coord_list = [tuple((a[0], a[1], -a[2])) for a in global_c]

In [78]:
global_coord_list

[(-122.39834830783556, 37.79515246607782, 3.0),
 (-122.39744999999897, 37.79248000012615, -0.0),
 (-122.39630693595093, 37.79337545780131, -0.0),
 (-122.39782909011151, 37.79615026622789, -0.0),
 (-122.4005777005116, 37.79335219860672, -0.0),
 (-122.39891969293332, 37.79191968249794, -0.0),
 (-122.39653459236686, 37.794710561515735, -0.0),
 (-122.39945825085853, 37.794139649856525, -0.0)]

In [79]:
for coord in global_coord_list:
    print (global_to_local(coord, global_coord))

[296.00001402 -81.          -3.        ]
[1.39954500e-05 1.62981451e-09 0.00000000e+00]
[100.00001402 100.           0.        ]
[407.00001404 -36.           0.        ]
[  95.00001399 -276.            0.        ]
[ -62.99998602 -129.            0.        ]
[248.00001403  79.           0.        ]
[ 183.000014 -178.          0.      ]


In [21]:
global_c

[array([-122.39323517,   37.7926577 ,    2.        ]),
 array([-122.396591,   37.793405,    5.      ]),
 array([-122.39544791,   37.79430045,    5.        ]),
 array([-122.39197118,   37.79305678,    5.        ]),
 array([-122.39553231,   37.79091196,    5.        ]),
 array([-122.39731596,   37.79224602,    5.        ]),
 array([-122.39376854,   37.79410254,    5.        ]),
 array([-122.39452568,   37.79179007,    5.        ])]

In [47]:
f = open ('colliders.csv')
first_row = f.readlines()[0].replace('\n','').split(', ')
f.close()
lat0 = float(first_row[0].strip('lat0 '))
lon0 = float(first_row[1].strip('lon0 '))
data = np.loadtxt('colliders.csv', delimiter=',', dtype='Float64', skiprows=2)

grid, north_offset, east_offset, grid_size = create_grid(data, 5, 5)

In [48]:
grid

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [52]:
global_home = (-122.396591, 37.793405, 5.0)

In [176]:
def random_goal(northrange, east_range, down_range, global_home, 
                start=(0,0,0), min_dist = 0):
    """
    Returns a random goal, expressed in NED format
    ((north, east, down)
    
    Args:
    north_range: tuple(min,max) all inclusive
    easth_range: tuple(min,max) all inclusive
    down_range: tuple(min,max) all inclusive
    global_home: global coordinates of the center of the NED map
    start: start location in NED format
    min_dist: integer representing the minimum distance between start and goal
    """
    dist = 0
    while dist < min_dist:
        ned_coord = (np.random.randint(north_range[0], north_range[1]+1),
        np.random.randint(east_range[0], east_range[1]+1),
        np.random.randint(down_range[0], down_range[1]+1))
        dist = np.linalg.norm(np.array(ned_coord) - np.array(start))     
    return ned_coord

In [188]:
global_home = (-122.396591, 37.793405, 0.0)
north_range = (-316,605)
east_range=(-445, 476)
down_range=(-100,0)
random_goal(north_range,east_range,down_range, global_home, min_dist = 300)

(41, 433, -44)

In [5]:
goal_ned = (569, -178, 18)
new_goal = list(goal_ned)
new_goal

[569, -178, 18]

In [6]:
new_goal.append(2)

In [7]:
new_goal

[569, -178, 18, 2]